### ISSUE TITLE
Layer Control Overflow

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/map-component#10]
Add a scrollbar to the layer control and / or support collapsible groups to prevent overflow of content:

![grafik](https://user-images.githubusercontent.com/1788226/52210231-acb85100-2886-11e9-9b10-50c6a7499479.png)

**Comment by therter** [comment]
The scrollbar was added and the layer groups can be collapsed/expanded. 

![map](https://user-images.githubusercontent.com/1788509/52434750-6a09a980-2b10-11e9-9add-664766b83e5c.png)
