### ISSUE TITLE
Decouple the study_variant from the Study Scenarios

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/map-component#100]
Ideally, we can decouple the study_variant from the Study Scenarios, so that it could be possible to show in the Map component the differences of the Study scenario with and without Adaptation options side by side (we already have the split screen with two maps, so we should use it). @therter let's maybe discuss this in a short telco to see how feasible that would be for us in the remaining time.

_Originally posted by @patrickkaleta in https://github.com/clarity-h2020/csis/issues/154#issuecomment-645846138_

**Comment by p-a-s-c-a-l** [comment]
What is feasible is to compare in the split-maps *either* between scenarios with / without adaptation *or* between scenarios (different combinations of rcp, time_period, event frequency) in general. I think we drop general scenario comparison in favour of baseline vs. adapted comparison since it makes more sense.

The important question here is: Do we support different adaptation scenarios or just one? If there is just one adaptation scenario which gets 'overwritten' when adaptation changes, this would make things more easy to implement. In this case, we can completely get rid the 'study_variant' (its always either baseline or adapted) and just have to introduce a property which indicates whether an adaptation scenario is available or not. In the opposite case we need a **separate** UI control element for selecting an adaptation scenario **in addition** to the general scenario.

For the table it might become more complicated if we need to show not only a mixture of  baseline vs adapted. but also of [PV and HW](https://github.com/clarity-h2020/emikat/issues/44).

**Comment by patrickkaleta** [comment]
> The important question here is: Do we support different adaptation scenarios or just one?

**I would stick to just one and currently the CSIS is configured to allow only one.** I've set it up so that in the future it can be adapted to allow more than just one, but that will require changes in the Drupal Views itself, in the csis_helpers module and in the REST interfaces used by Emikat. We the limited hours I got left, it just doesn't seem very realistic.

**Comment by p-a-s-c-a-l** [comment]
@patrickkaleta 

How can I test the new `has_adapted_scenario: ` flag? It seems that it is not yet available on PROD and on DEV I cannot recalculate studies to include Adaptation Options.

**Comment by p-a-s-c-a-l** [comment]
I've tried to recalculate [study 35](https://csis.myclimateservice.eu/study/35/view/intro) to get an adaptation scenario, but the process is stuck at "14 out of 17 processes". @DenoBeno @humerh ?

**Comment by p-a-s-c-a-l** [comment]
I've recalculated [study 35](https://csis.myclimateservice.eu/study/35/view/intro) and but still there are no [adaptation results](https://service.emikat.at/EmiKatTst/api/scenarios/3189/feature/view.2975/table/data?rownum=100000) available.

I've created an [adaptation strategy](https://csis.myclimateservice.eu/study/35/step/1526/view/table) but it doesn't seem to get applied. Anything else I need to do get an adaptation scenario? @DenoBeno @fabrisj @humerh @patrickkaleta

**Comment by patrickkaleta** [comment]
> @patrickkaleta
> 
> How can I test the new `has_adapted_scenario: ` flag? It seems that it is not yet available on PROD and on DEV I cannot recalculate studies to include Adaptation Options.

I can update the csis_helpers module on PROD (by pulling the latest version from the git repository). I haven't done so yet, since I wanted to await testing on DEV first. But you're right, it's hard to test this when you're not allowed to trigger Emikat calculations on DEV. 

@p-a-s-c-a-l  are you performing any updates on the Docker containers currently? Because I had troubles accessing DEV and PROD for a while, DEV seems still unavailable at the moment.

**Comment by patrickkaleta** [comment]
> I've recalculated [study 35](https://csis.myclimateservice.eu/study/35/view/intro) and but still there are no [adaptation results](https://service.emikat.at/EmiKatTst/api/scenarios/3189/feature/view.2975/table/data?rownum=100000) available.

I can see some results for the Adaptation Strategy. Looking at the HC-LE table, I can see results for [baseline](https://service.emikat.at/EmiKatTst/api/scenarios/3189/feature/view.2974/table/data?rownum=1000&filter=STUDY_VARIANT%3D%27BASELINE%27&filter=TIME_PERIOD%3D%2720410101-20701231%27&filter=EMISSIONS_SCENARIO%3D%27rcp45%27&filter=EVENT_FREQUENCY%3D%27Rare%27&column=GRID_ID&column=STUDY_VARIANT&column=TIME_PERIOD&column=EMISSIONS_SCENARIO&column=EVENT_FREQUENCY&column=T_MRT&column=T_UTCI&column=T_A&column=DISCOMFORT_LEVEL) and for the [adapted scenario](https://service.emikat.at/EmiKatTst/api/scenarios/3189/feature/view.2974/table/data?rownum=1000&filter=STUDY_VARIANT%3D%27ADAPTATION-01%27&filter=TIME_PERIOD%3D%2720410101-20701231%27&filter=EMISSIONS_SCENARIO%3D%27rcp45%27&filter=EVENT_FREQUENCY%3D%27Rare%27&column=GRID_ID&column=STUDY_VARIANT&column=TIME_PERIOD&column=EMISSIONS_SCENARIO&column=EVENT_FREQUENCY&column=T_MRT&column=T_UTCI&column=T_A&column=DISCOMFORT_LEVEL).

**Comment by p-a-s-c-a-l** [comment]
Thanks @patrickkaleta. Yes, I performed a backup of the database and had to shut it down. 

Yes, there are now adaptation results available and I can show them on the [map](https://csis.myclimateservice.eu/study/35/step/1528/view/maps):

![image](https://user-images.githubusercontent.com/1788226/88372313-edb36680-cd95-11ea-9eeb-7e5ea1a642a0.png)
