### ISSUE TITLE
Retrieve all overlay layers from the data package

### ISSUE THREAD

**Issue by therter** [clarity-h2020/map-component#14]
All overlay layers for the maps should be retrieved from the data package. If the data package does not contain any layer for a map, default layers should be used

**Comment by maesbri** [comment]
I think the csis should come already preconfigured with some background layers from OSM, and add on top of it the ones available in the data package.

**Comment by therter** [comment]
@maesbri yes that is correct. The used API differs between the base layers (background layers), which are preconfigured (and only one can be selected at a time) and the overlay layers, which will be retrieved from the data package.
