### ISSUE TITLE
Map loads wrong HC-LE layers

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/map-component#15]
Maps shows the correct HC-LE layers (4 HW Events) but suddenly reloads the layers (probably from the Data Package) and shows HC-LE **input layers** (they as background  layers, see #3 )

![fubar](https://user-images.githubusercontent.com/1788226/54361751-fce5b880-4667-11e9-9a82-458e9f0442f6.gif)

Correct behaviour: 
- Map should't show layers which are replaces later
- Correct HC-LE Layers have to be added to the Data Package
- instead of 'relevant layer' the real category (HW Event..) has to be shown

**Comment by therter** [comment]
The Map does not show layers which are replaces later and the category "relevant layer" will not be shown. Layers, which are not assigned to a hazard, will not be shown.
