### ISSUE TITLE
Loading of map layer names takes forever

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/map-component#18]
Not sure where the map widgets are gettign the names for the available layers from, but this takes forever. Should be optimized (e.g. just one REST call, cached...)

**Comment by therter** [comment]
The [include](https://www.drupal.org/docs/8/modules/jsonapi/includes) parameter is now used to get the sub objects of the data package resources with one jsonapi call. This improves the performance.

**Comment by DenoBeno** [comment]
good
