### ISSUE TITLE
Suggestion for improving the map component

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/map-component#21]
Claudia has suggested to improve the map component by making it more similar to http://swicca.eu/climate-impacts-maps/

The required information *should* be in data package and if this isn't foreseen yet, the data package information should be extended.

![grafik](https://user-images.githubusercontent.com/1788226/56199696-b1934100-603d-11e9-8ea0-6d02b9ffeace.png)

**Comment by stefanon** [comment]
Most important improvement needed I think is the legenda visualization with scale and units of values shown in the map, and the identify function if possible.

**Comment by p-a-s-c-a-l** [comment]
Legend can be obtained via getLegend request, right? Is this configured at METEOGRID GeoServer? Do we need a separate entry in data package meta-data?

**Comment by therter** [comment]
> Legend can be obtained via getLegend request, right? 

This is right and the  METEOGRID WMS has the legend configured.

> Do we need a separate entry in data package meta-data?

I can get the request via the GetCapabilities document of the wms. All I need is the layer name and the style name and this information is contained within the data package

**Comment by p-a-s-c-a-l** [comment]
Any updates regarding the legend?

**Comment by therter** [comment]
The legend of the currently selected layer will be shown on the left side of the map

![Auswahl_123](https://user-images.githubusercontent.com/1788509/57851583-38743e80-77e1-11e9-99f9-8d64d7f8136c.png)

**Comment by p-a-s-c-a-l** [comment]
Yes, I know. Please consider the following comment:

> Most important improvement needed I think is the legenda visualization with scale and **units of values** shown in the map, and the identify function if possible.

So legends have to be improved. It's not clar whaT's shown on the map. 25-30 WHAT?

**Comment by p-a-s-c-a-l** [comment]
Any progress here?

**Comment by p-a-s-c-a-l** [comment]
> Any progress here?

**Comment by DenoBeno** [comment]
I can't do anything on a map, getting myself out of the loop.

**Comment by claudiahahn** [comment]
I just realised that: 
- when selecting e.g. summerdays rcp85 - 2071-2100: the legend is too long and not properly shown anymore, units are not displayed because the legend is too long
![grafik](https://user-images.githubusercontent.com/45260352/65411038-1cfeed00-ddec-11e9-8013-044415dd7bec.png)

- there is no title yet (I know, there are more pressing issues right now), but if there is time: it would be very helpful for the user to also see a title, such that they know what they are looking at

**Comment by p-a-s-c-a-l** [comment]
Regarding the size of the legend, imho we have no influence on that, right @therter ? 
So the only possibility would be to increase the height of the map component.

Regarding the missing title/unit, imho this is something that has to be configured in the WMS, so maybe @LauraMTG  or @ghilbrae can have a look?

**Comment by therter** [comment]
> Regarding the size of the legend, imho we have no influence on that, right

At the moment, the legend has the same size as the image, we retrieve from the wms. But we can use css to scale down every legend image to 80% for example.
