### ISSUE TITLE
Make infos about the current map available for the "Include in Report" functionality. 

### ISSUE THREAD

**Issue by therter** [clarity-h2020/map-component#22]
The map-component should deliver data about the current map (zoom, bounding box, ...), so that the "Include in Report" functionality can use this information to generate a comment about the map.

**Comment by therter** [comment]
The maps have now a hidden div element with the id reportInfoElement and the following content:

`zoom level:14 bounding box: 14.195451736450197,40.8258257213893,14.287977218627931,40.85829183049755`

The content will be refreshed when the view port of the map was changed.

@patrickkaleta Are there any additional information required,

**Comment by therter** [comment]
> Maybe the title of the active layer?

@patrickkaleta Yes, I think the title is useful. I will add it

**Comment by patrickkaleta** [comment]
The [CSIS helpers module](https://github.com/clarity-h2020/csis-helpers-module) now takes the content of this hidden div element as input for the comment field.

**Comment by p-a-s-c-a-l** [comment]
This won't work any more , when we've switched to [iFrames](https://github.com/clarity-h2020/map-component/issues/37)! But I consider this particular feature less important. General support for [iFrames in Report](https://github.com/clarity-h2020/csis-helpers-module/issues/13) should be implemented first. Then we'll see if and how to restore this feature.

**Comment by p-a-s-c-a-l** [comment]
KISS
