### ISSUE TITLE
Additional Background Map Layers 

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/map-component#3]
Follow the same top-down approach as described [here](https://github.com/clarity-h2020/csis/issues/46#issue-390262842) and [here](https://github.com/clarity-h2020/table-components/issues/1#issue-390284000). Design a simple  internal state model and implement a dynamic layer control widget for HC / EE / etc. layer groups. Last step is then to implement [Data Package Support](https://github.com/clarity-h2020/map-component/issues/2). Input for the design of the state model and initial example layers can be found in [these issues](https://github.com/clarity-h2020/data-package/milestone/1)

Note that we distinguish between 2 types of background layers: static (global layers, e.g. OSM) and [dynamic layers](https://github.com/clarity-h2020/data-package/issues/5) (loaded from the data package, e.g. detailed city plan). 

Static layers (Example: "Hintergrundkarte") could be put in a separate drop-down as shown below:

![kdb](https://user-images.githubusercontent.com/1788226/49882687-6c61c700-fe31-11e8-978f-dd128a85773d.gif)

Dynamic (background) layers can be categorised, too (Example: "Topographische Karten"). HC / EE /IA, etc. layers are only visible in the respective step.

**Comment by therter** [comment]
The maps can be categorised and the categories can be expanded/collapsed. See also #10

**Comment by RobAndGo** [comment]
I hope this comment belongs here - it concerns the map layers showing the heat-wave hazards here: https://csis.myclimateservice.eu/study/1/step/2/view/maps
(Sorry, I only now just discovered this portal to view the CSIS ![gaah](https://user-images.githubusercontent.com/45385637/55319749-e025ef00-5475-11e9-8b85-85093de69815.gif) ) 

It seems as though the layers are lacking information. For example, when I click on this map:
![2019-04-01_120757](https://user-images.githubusercontent.com/45385637/55320208-dd77c980-5476-11e9-9b9c-22f555c62b47.png)

it does not show the same amount of detail as in the original map for the same period/RCP scenario:
![Tx75p_consecutive_max_2071-2100_rcp45](https://user-images.githubusercontent.com/45385637/55320225-e49ed780-5476-11e9-9082-86689d8d921f.png)

This comment applies to all of the periods/RCP scenarios clickable for the heat waves.

**Comment by p-a-s-c-a-l** [comment]
@therter @luis-meteogrid @ghilbrae 
Any comments to @RobAndGo's [question](https://github.com/RobAndGo)?

**Comment by ghilbrae** [comment]
Hi! We've looked into it and it's a problem with the scale. We've tested a new scale with that same layer and this is the result for that same layer:
![scale](https://user-images.githubusercontent.com/1615745/58537596-731fa300-81f3-11e9-83b0-994049462262.png)

The scale we've used is this one:
```
              <ColorMapEntry color="#fff" quantity="0" label="0" />
              <ColorMapEntry color="#7b41f7" quantity="6" label="6" />
              <ColorMapEntry color="#425dff" quantity="12" label="12" />
              <ColorMapEntry color="#39b2ff" quantity="18" label="18" />
              <ColorMapEntry color="#39ffde" quantity="24" label="24" />
              <ColorMapEntry color="#8cff39" quantity="30" label="30" />
              <ColorMapEntry color="#ffff42" quantity="36" label="36" />
              <ColorMapEntry color="#ffb24a" quantity="42" label="42" />
              <ColorMapEntry color="#ff4d39" quantity="48" label="48" />
              <ColorMapEntry color="#ad0000" quantity="54" label="54" />
              <ColorMapEntry color="#630000" quantity="60" label="60" />
```

Let us know if this is ok for you @RobAndGo so we may use it for the other heat wave layers. We can use any other scale you'd like us to use, but please let us know the colours' codes.

**Comment by therter** [comment]
@ghilbrae Can you please add the units of the values to the legend

**Comment by ghilbrae** [comment]
@therter done, we've added a first line with that info. Let us know if this works for you. There's not an easy way to do it other than editing the labels from the style (if we find a better option we'll try it).

**Comment by RobAndGo** [comment]
Sorry for my very late reply, but yes, the colour scale does look much better!
