### ISSUE TITLE
The GroupedLayerControl element is not shown properly after a mouseover event

### ISSUE THREAD

**Issue by therter** [clarity-h2020/map-component#41]
The style property max-height of the expanded GroupedLayerControl element is set to "0px". So the content of the element will not be shown after a mouse over event. 
The reason for this is that the initialisation of the map-component happens while the "Analysis Map" tab is collapsed and the height of the react component is 0px.

**Comment by p-a-s-c-a-l** [comment]
How to resolve this? Can this be changed in the respective Drupal View or is it a general problem of [the new theme](https://github.com/clarity-h2020/clarity-theme/issues)?

**Comment by therter** [comment]
The max-height of the expanded GroupedLayerControl element can set to 465px via javascript (within the body of the "React Mount with JS" content type), to solve this problem. 

After the switch from React Mount Node to an iFrame, the component should work without this workaround.

**Comment by p-a-s-c-a-l** [comment]
>  initialisation of the map-component happens while the "Analysis Map" tab is collapsed

That the root cause of the problem. Can it be prevented?

**Comment by p-a-s-c-a-l** [comment]
Not relevant any more in https://github.com/clarity-h2020/map-component/issues/37
