### ISSUE TITLE
Support for CI

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/map-component#45]
Create Jenkinsfile and tell and update CI server to use it.

**Comment by p-a-s-c-a-l** [comment]
@DanielRodera I configured the [map-component CI project](http://5.79.69.49/job/map-component) in Jenkins, but when I execute it, it seems to [run forever](http://5.79.69.49/job/map-component/3/console) (probably the same problem as with the [simple-table-component](https://github.com/clarity-h2020/simple-table-component/issues/3#issuecomment-524308940)).

**Comment by DanielRodera** [comment]
I have updated the Jenkinsfile. Now is working properly:

![image](https://user-images.githubusercontent.com/42216407/63770352-4b64d780-c8d5-11e9-8e6a-ba7cf9c1a503.png)

I also solved the problem related to the following image: 

![image](https://user-images.githubusercontent.com/42216407/63770204-ea3d0400-c8d4-11e9-9492-8fe18c2c3236.png)

**Comment by p-a-s-c-a-l** [comment]
Update Hook URI once https://github.com/clarity-h2020/simple-table-component/issues/3#issuecomment-541049553 is resolved.

**Comment by p-a-s-c-a-l** [comment]
done
