### ISSUE TITLE
Emikat "population" map not showing up properly.

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/map-component#49]
I am not 100% sure what is wrong, but the result is that the map shows population data in Naples although the study area is set for Stockholm.

Here is how to check:

- https://csis.myclimateservice.eu/study/25/view/data shows the map with all resources, choose population and see that only the population in Naples is shown.
- https://csis.myclimateservice.eu/group/25/edit indicates that emikat ID is 3183. This is correct, according to emikat client interface

![image](https://user-images.githubusercontent.com/2961790/63862852-8f2b1000-c9ad-11e9-8027-dcf383343d26.png)

- Initially, the EMIKAT data tables were not built. Not sure if this was caused by the errors on group update, but I have restarted the calculations manually and now all should be OK. @humerh , please check if the generated data is correct. @patrickkaleta , please check if the table generation is triggered correctly. 

**Note:** generating the tables in EMIKAT takes some time. Users should be told this.

- Finally, the error could be in the map component too. @therter , please double-check if the map component is using correct emikat ID.

**Comment by DenoBeno** [comment]
Update: I just looked up again and the data is now available in Stockholm

road transport layer:

![image](https://user-images.githubusercontent.com/2961790/63875361-9ceb9000-c9c3-11e9-9290-5d14a71f8c20.png)

Population layer:
![image](https://user-images.githubusercontent.com/2961790/63875398-aa087f00-c9c3-11e9-9de5-a57850c9a3b5.png)

**Comment by DenoBeno** [comment]
Btw, we really need some kind of an "empty map" background. E.g. just city names & administrative borders, but no colorful background.

**Comment by DenoBeno** [comment]
@humerh : did you change anything on emikat side?

**Comment by humerh** [comment]
Yes, there was an error in the interface between Geoserver and Emikat. 
I fixed the error!

**Comment by p-a-s-c-a-l** [comment]
European Population Distribution is now shown on [the map](https://csis.myclimateservice.eu/apps/map-component/build/StudyPreviewMap/?host=https://csis.myclimateservice.eu&study_uuid=9359e741-df40-4bcd-9faf-2093b499c65c&study_area=POLYGON%20((17.884345%2059.334569,%2017.884345%2059.381605,%2018.029227%2059.381605,%2018.029227%2059.334569,%2017.884345%2059.334569))&emikat_id=3183&datapackage_uuid=2434ce93-93d4-4ca2-8618-a2de768d3f16&write_permissions=1&grouping_tag=taxonomy_term--eu_gl):

![grafik](https://user-images.githubusercontent.com/1788226/64423093-f3cd2580-d0a5-11e9-8cbf-1099a5f6a180.png)


Support for additional parameters beyond `$emikat_id` is discussed [here](https://github.com/clarity-h2020/data-package/issues/42).
