### ISSUE TITLE
Encoded URLs not supported

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/map-component#50]
See https://github.com/clarity-h2020/data-package/issues/41#issuecomment-526095463.

Possible solution: apply decodeURI() before analysing and reconstructing the URI.

**Comment by therter** [comment]
> Possible solution: apply decodeURI() before analysing and reconstructing the URI.

I don't know why, but decodeURI() does not work. 
The function decodeURIComponent() works, when I use it in the extractLayers(url) and extractStyle(url) functions to decode the return value.

**Comment by p-a-s-c-a-l** [comment]
Implemented in [feature/037-iframe](https://github.com/clarity-h2020/map-component/tree/feature/037-iframe)
