### ISSUE TITLE
StudyAreaMap: The requirement of cities should depend on the study 

### ISSUE THREAD

**Issue by therter** [clarity-h2020/map-component#55]
At the moment, the user has to select a city before it is allowed to select a study area. But for some study types, it should be possible to choose study areas outside of the defined cities. In the first step, this should be possible for all study types, which have not the study calculation type "EMIKAT screening"

**Comment by p-a-s-c-a-l** [comment]
status?

**Comment by therter** [comment]
This is working. The used branch is feature/55_study_area_without_city
