### ISSUE TITLE
Study Area Map: Disable unnecessary edit controls

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/map-component#57]
Disable all edit controls but rectangle:

![grafik](https://user-images.githubusercontent.com/1788226/65603606-46637880-dfa6-11e9-8cfd-c76fbd71fe32.png)

**Comment by therter** [comment]
I can remove the edit controls. The study area map will then look like this:

![Bildschirmfoto vom 2019-09-25 20-24-14](https://user-images.githubusercontent.com/1788509/65628850-91938080-dfd2-11e9-9c51-1828d2d97f4d.png)

**Comment by therter** [comment]
The used branch is feature/57_study_area_remove_edit_controls that is based on feature/55_study_area_without_city
