### ISSUE TITLE
How to implement better/more useful map component(s)?

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/map-component#59]
As of today, it seems that we have a working map component, so it's time to think about the possible improvements. Here are some I can think of, for discussion:

- [x] **1. avoid resetting after taking a screenshot.** 
Implemented, see https://github.com/clarity-h2020/map-component/issues/58

- [ ] **1b. avoid resetting after changing a preset.** 
This is currently the case (03/02/2020), see https://github.com/clarity-h2020/map-component/issues/83

- [ ] **2. Show the active layer title and/or add it to the screenshot description.**
We used to have some information automatically added to screenshot description, that's gone now. 

- [x] **3. Show two maps instead of one for a side to side comparison.** 
These maps should have same zoom & pan, but different layers and the screenshot should show them both. Possibly even a third one with a diff? Or one map for each preset?

![image](https://user-images.githubusercontent.com/2961790/66211240-ebbfd000-e6bb-11e9-9d92-3b1679113465.png)

- [ ] **4. show information for a grid cell** 
E.g. next to a map show a data for a grid cell on click, so that a screenshot can be taken. The active cell should be somehow highlighted on the map. Alternatively, user could choose several cells and a summary for them is shown (total, average, min/max)

- [ ] **5. allow user to overlay several layers and decide how to colour-code each** 
Claudia has proposed this as a way to rapidly get an idea of where the main issues in the project area are. See https://github.com/clarity-h2020/csis/issues/105#issuecomment-537927714 

WDYT? 

PS: This are just some ideas that I wanted to write down before forgetting them, feel free to add more. 
PPS: Somewhat obvious, but we should do easy & useful things first, not waste time with tricky ones.
PPPS: who should we include in discussion?

**Comment by DenoBeno** [comment]
related to https://github.com/clarity-h2020/csis/issues/105#issuecomment-537927714, I will add the wish number 5 to the list: a possibility to show several layers on a map and colour-code them differently. 

As noted on https://github.com/clarity-h2020/csis/issues/105#issuecomment-538019284, this *could* also be done server-side by calculating one layer from several input layers, but that requires more effort up-front and leaves less options for the user later. It's basically a difference between designing a tool for experts (e.g. consultants) and DAO users in my opinion.

**Comment by DenoBeno** [comment]
My recent testing has clearly shown that the colour coding (e.g. for the hazard layers is not ideal. Basically, I wasn't able to say by how much the data changed in different scenarios. Was it 50 summer days, 70 or 90?

What can we do about this?

**Comment by claudiahahn** [comment]
> My recent testing has clearly shown that the colour coding (e.g. for the hazard layers is not ideal. Basically, I wasn't able to say by how much the data changed in different scenarios. Was it 50 summer days, 70 or 90?
What can we do about this?

It would be possible to display a change layer instead of the actual climate index for the future periods and different scenarios. One could then display the baseline and next to it display the change layer (% change) In that case we would need to add additional resources of course

**Comment by p-a-s-c-a-l** [comment]
I've implemented support for synchronised maps and enabled it for the [HC-LE Step](https://csis.myclimateservice.eu/study/35/step/1524/view/maps) (currently just for testing purposes):

![synchronised-map-component](https://user-images.githubusercontent.com/1788226/76625337-4ac12500-6537-11ea-8d21-0c917b2d1d5c.gif)

**Comment by DenoBeno** [comment]
I bumped into this today, while testing if the EMIKAT calculations work. It's really nice and seems to work well. What would be even nicer is if I could compare the same indice for two different scenarios.

**Comment by DenoBeno** [comment]
The http://services.clarity-h2020.eu:8080/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Acity&bbox=1969465.0%2C996016.875%2C7168551.0%2C4677889.0&width=768&height=543&srs=EPSG%3A3035&styles=hw_availability&format=text%2Fhtml%3B%20subtype%3Dopenlayers#toggle reminded me of the wish to see the value of the data field when clicking on a map somewhere. 

![image](https://user-images.githubusercontent.com/2961790/78154420-89fadb80-743c-11ea-8796-b9cc68656b15.png)

As it is, I really can't say how many days is each of the fields on the screenshot below. 

![image](https://user-images.githubusercontent.com/2961790/78154735-e5c56480-743c-11ea-8fde-64c696278984.png)

Or even what the two maps are showing. :-( 
For the record, it's summer days (left) and tropical nights (right). So, how many tropical nights is it, would you say? Around 30? or around 70?

When I zoom out, I can see that it's not around 72, but still - this is quite difficult to interpret.

**Comment by p-a-s-c-a-l** [comment]
@therter This information could be obtained by a *getFeatureInfo* request, if the server supports it, right? 
But what, if more than one layer is selected as it is usually the case in the map component?

**Comment by therter** [comment]
> @therter This information could be obtained by a _getFeatureInfo_ request, if the server supports it, right?

Yes, this is right. But this is an optional operation, so not every wms supports this.

**Comment by p-a-s-c-a-l** [comment]
- 1b. avoid resetting after changing a preset: wontfix: iFrame has to be reloaded
-  2. Show the active layer title and/or add it to the screenshot description: layer title now shown in the legend
- see the value of the data field when clicking on a map somewhere: there are a lot of different values in each layer and when several layers are active, it's not clear what shall be shown to whom for which purpose.
