### ISSUE TITLE
Country taxonomy will not be shown

### ISSUE THREAD

**Issue by therter** [clarity-h2020/map-component#6]
and check the maximum size of the area

**Comment by p-a-s-c-a-l** [comment]
Warning: Each child in an array or iterator should have a unique "key" prop.

Check the render method of `MapComponent`. See https://fb.me/react-warning-keys for more information.
    in WMSTileLayer (created by MapComponent)
    in MapComponent (created by CharacteriseHazardMap)
    in CharacteriseHazardMap

**Comment by p-a-s-c-a-l** [comment]
Gemischte (unsichere) Anzeige-Inhalte von "http://5.79.69.33:8080/geoserver/clarity?service=WMS&request=GetMap&layers=it003l3_napoli_ua2012_biuldings&styles=&format=image%2Fjpeg&transparent=true&version=1.1.1&width=256&height=256&srs=EPSG%3A3857&bbox=-20037508.342789244,-20037508.34278071,20037508.342789244,20037508.34278071" werden auf einer sicheren Seite geladen[Weitere Informationen]

**Comment by p-a-s-c-a-l** [comment]
@negroscuro please add https to your geoserver instance
