### ISSUE TITLE
No risk/impact data shown in table & map for the future

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/map-component#60]
As I implemented https://github.com/clarity-h2020/csis/issues/109, I quickly realised that no risk/impact map shows for the future. Not sure what is causing it:

- emikat not generating the map?
- map component not asking for it corerctly?
- emikat filters broken?

![grafik](https://user-images.githubusercontent.com/2961790/66126203-37557980-e5e9-11e9-8f62-09089836f7d4.png)

The variables from csis helpers ook OK...

![grafik](https://user-images.githubusercontent.com/2961790/66126461-c2367400-e5e9-11e9-9677-83f09c02ca43.png)

**Comment by DenoBeno** [comment]
Seems to be EMIKAT

`https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:view.2975&bbox=4672000.0,1979500.0,4687500.0,1988000.0&width=768&height=421&srs=EPSG:3035&format=image/gif&CQL_FILTER=STUDY_VARIANT=%27BASELINE%27%20and%20TIME_PERIOD=%2720410101-20701231%27%20AND%20EMISSIONS_SCENARIO=%27rcp45%27%20AND%20EVENT_FREQUENCY=%27Rare%27%20AND%20SZ_ID=3189`

result: 

![grafik](https://user-images.githubusercontent.com/2961790/66126983-037b5380-e5eb-11e9-9352-9ecfe0365b1e.png)

**Comment by DenoBeno** [comment]
OK, we have the same isue for the table - except that this works

https://csis.myclimateservice.eu/apps/simple-table-component/build/?emikat_id=3189&time_period=20110101-20401231&emissions_scenario=rcp45&event_frequency=Frequent

but this doesn't, except for the "historical" period.

https://csis.myclimateservice.eu/study/33/step/1517/view/table

@therter: not sure about the first, but at least the second one is for you. Unless the variable values are wrong - this can be easily fixed by editing the taxonomy (https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/dp_variable_meanings/overview) but it looks OK to me.

**Comment by DenoBeno** [comment]
FYI, I have added the emikat ID to the view, to ease debugging.

![grafik](https://user-images.githubusercontent.com/2961790/66128493-32df8f80-e5ee-11e9-80bf-3b851344fba9.png)

![grafik](https://user-images.githubusercontent.com/2961790/66128523-4559c900-e5ee-11e9-81e5-0d915652298c.png)

**Comment by humerh** [comment]
Ein günstiger Ausschnitt für diese Study-Area:
https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:view.2975&bbox=5523000,1755000,5535000,1760000&width=768&height=421&srs=EPSG:3035&format=image/gif&CQL_FILTER=STUDY_VARIANT=%27BASELINE%27%20and%20TIME_PERIOD=%2720410101-20701231%27%20AND%20EMISSIONS_SCENARIO=%27rcp45%27%20AND%20EVENT_FREQUENCY=%27Rare%27%20AND%20SZ_ID=3189

**Comment by DenoBeno** [comment]
Wait!

They all look the same. Are you sure that filters work?

**Comment by therter** [comment]
> So if EMIKAT side works now, then we have an issue with the map component now. @therter , please check.

The map component retrieves an empty layer image from the emikat wms for all time periods except Baseline. So I think, there were no data calculated for the future time periods. 

> Btw, the table view is even more broken now: https://csis.myclimateservice.eu/study/35/step/1528/view/table

The problem with the table component is the attribute  filter=SZ_ID=3189 in the emikat request. The server responds with 
`Error during data retrieval - EMIKAT-Server.DB.ConnectionProblem: Can't access db: java.sql.SQLSyntaxErrorException: ORA-00904: "SZ_ID": ungültiger Bezeichner - `
when the attribute SZ_ID is used within the request. Is this attribute not used anymore?

**Comment by therter** [comment]
> Is this attribute not used anymore?

And if this is the case, I can remove the SZ_ID  attribute from the resource (https://csis.myclimateservice.eu/node/1356) and the table should work again.

**Comment by DenoBeno** [comment]
I don't know. Yesterday https://csis.myclimateservice.eu/apps/simple-table-component/build/?emikat_id=3189&time_period=20110101-20401231&emissions_scenario=rcp45&event_frequency=Frequent worked, so I suppose it's Heinrich who changed something. 

As for the map layers, yesterday they were showing empty result for anything in the future, earlier today they were showing the same results for all filter combinations. I'll call Heinrich again. :-(

**Comment by DenoBeno** [comment]
SZ_ID is indeed not needed any-more with tables. 

As for the map, Patrick and I double checked this now and the issue is that the map widget always requests the "Baseline" scenario. Guess it's not taking the variable correctly from the csis helpers.

**Comment by therter** [comment]
>     1. SZ_ID is indeed not needed any-more with tables. Sorry.

I have removed this attribute

> As for the map, Patrick and I double checked this now and the issue is that the map widget always requests the "Baseline" scenario. Guess it's not taking the variable correctly from the csis helpers.

A wrong parameter name was used (emission_scenario instead of emissions_scenario). The map and the table should now work

**Comment by DenoBeno** [comment]
Now, that's something completely different! :-)

![](file:///tmp/Screenshot_2019-10-04_15-27-13.png)

I'm closing this before somethign bad happens again.

**Comment by p-a-s-c-a-l** [comment]
> A wrong parameter name was used (emission_scenario instead of emissions_scenario).

where?

**Comment by therter** [comment]
The wrong parameter was used in the csis-helpers-module. See clarity-h2020/csis-helpers-module#15
