### ISSUE TITLE
EMIKAT not showing correct map after change of study location

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/map-component#61]
This is probably EMIKAT caching issue, but I'm reporting iit under map because it concerns map component too.

When the study area is changed, EMIKAT still shows the data for the old area. I double-checked the situation and EMIKAT does get the right coordinates so it seems to be an issue with caching.

Furthermore, on next change of area the area shown will be changed to one before the last again. generally, on N-th change, the N-1 area will be shown.

![Screenshot_2019-10-04_12-14-35](https://user-images.githubusercontent.com/2961790/66200167-bd80c700-e6a0-11e9-840d-54271bcf9335.png)

**Comment by DenoBeno** [comment]
I just reloaded the same map again and all is OK. It's definitely some kind of a caching issue, I'm just not sure if the map component or the EMIKAT is responsible. 

![image](https://user-images.githubusercontent.com/2961790/66201109-ca061f00-e6a2-11e9-808f-da70aebdca17.png)

**Comment by p-a-s-c-a-l** [comment]
Changing the study are is a feature we should disable when the system goes life. For development and testing it's o.k., but in production we don't need it IMO. If the the user want a new area -> new study.

**Comment by DenoBeno** [comment]
I'm not so sure. 
It's far too easy to take a wrong area per mistake. There may be valid reasons to do the calculation with several areas too...

As for changing the study type, that's a pretty destructive task. Maybe it should be disabled. At very least, it should be made more difficult (THIS WILL WIPE UP ALL PROJECT DATA, DO YOU REALLY WANT TO PROCEED? [NO WAY] [DEFINITELY NOT] [LET ME RETHINK] [yes, i really want to])

;-)
