### ISSUE TITLE
Study area starts moving after taking first screenshot

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/map-component#63]
After implementing the new feature (#58) of the page not to reload after a screenshot is taken, I noticed that the study area starts moving once the user is either moving in the map or zooming in or out of it. This is both the case for the Study area map (e.g. [here](https://csis.myclimateservice.eu/study/35/view/area)), as well as for the individual maps in each GL-step (e.g. [here](https://csis.myclimateservice.eu/study/33/step/1519/view/maps)).

The two most recent screenshots in the summary tab in [Study 35](https://csis.myclimateservice.eu/study/35/view/summary) show how this effect looks like.

@therter I'm guessing this might have something to do with the `replaceTranslate3dStyle `functions in the [csis_include_in_report.js](https://github.com/clarity-h2020/csis-helpers-module/blob/dev/js/csis_include_in_report.js). Maybe this somehow needs to be reset before taking any additional new screenshots. Can you please have a look at this?

**Comment by therter** [comment]
> I'm guessing this might have something to do with the `replaceTranslate3dStyle `functions in the [csis_include_in_report.js](https://github.com/clarity-h2020/csis-helpers-module/blob/dev/js/csis_include_in_report.js).

That was the reason for the wrong study area after a screenshot was taken. But with the onclone parameter of the html2canvas function, this could be fixed.
