### ISSUE TITLE
Map component not calling the correct legend for EMIKAT local heat resource(s)

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/map-component#64]
When asking for any of the three EMIKAT temperature layers on this step https://csis.myclimateservice.eu/study/30/step/1613/view/maps ...

This is what the map component asks for:

`https://service.emikat.at/geoserver/clarity/wms?service=WMS&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=clarity:view.2974`
together with this map call
`https://service.emikat.at/geoserver/clarity/wms?CQL_FILTER=STUDY_VARIANT=%27BASELINE%27%20and%20TIME_PERIOD=%2720410101-20701231%27%20AND%20EMISSIONS_SCENARIO=%27rcp45%27%20AND%20EVENT_FREQUENCY=%27Frequent%27%20AND%20SZ_ID=3210&&service=WMS&request=GetMap&layers=clarity%3Aview.2974&styles=T_UTCI%0D%0A&format=image%2Fpng&transparent=true&version=1.1.1&leaflet=%5Bobject%20Object%5D&width=1536&height=1536&srs=EPSG%3A3857&tileSize=1536&attribution=&bbox=1829596.7090339793,6139422.1118653575,1836934.663749356,6146760.066580737`
This is wrong, because EMIKAT produces three scales, one for T_A, one for T_UTCI and one for radiant temperature.

HOWEVER, `https://service.emikat.at/geoserver/clarity/wms?service=WMS&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=clarity:view.2974&styles=T_A` doesn't work properly. @humerh ?

**Comment by DenoBeno** [comment]
I found it (praised be the GetCapabiliites)

`https://service.emikat.at/geoserver/clarity/wms?service=WMS&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=clarity:view.2974&style=clarity:T_A`

so, it must be one of the following:

- style=clarity:T_A
- style=clarity:T_UTCI
- style=clarity:T_MRT

At the moment only the T_A is different, but all three need to be rescaled.

**Comment by therter** [comment]
The style parameter for the legend request is now used by the map-component. But the local effect layers (Local effect UTCI temperature, Local effect apparent temperature and 
Local effect mean radiant temperature) have no data at the moment.

**Comment by p-a-s-c-a-l** [comment]
Any news regarding this issue?

**Comment by DenoBeno** [comment]
this is working now
