### ISSUE TITLE
Please allow choosing more than one map layer

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/map-component#65]
Related to https://github.com/clarity-h2020/map-component/issues/59, issue no. 5

- [ ] **5. allow user to overlay several layers and decide how to colour-code each** 
Claudia has proposed this as a way to rapidly get an idea of where the main issues in the project area are. See https://github.com/clarity-h2020/csis/issues/105#issuecomment-537927714 

The easiest way to achieve this (at least the "show several layers" part) would IMO be by allowing the users to select more than one layer. This isn't a greatest thing in terms of the usability, but it should be easy to do.

The use case described by claudia should not be hindered by layer overlaps - it's either  awood or it's a park or it's a lake or it's a house, never all of it together...

@p-a-s-c-a-l , @claudiahahn  WDYT?

**Comment by claudiahahn** [comment]
> The easiest way to achieve this (at least the "show several layers" part) would IMO be by allowing the users to select more than one layer.

I agree. I could imagne that is what a user is interested in. To see potentially hot and potentially cool places at once

> The use case described by claudia should not be hindered by layer overlaps - it's either awood or it's a park or it's a lake or it's a house, never all of it together...

That is true. The layers were defined based on urban atlas data only and the layers don't overlap. Selecting an additional layer would just lead to another area being displayed with a different color.

**Comment by p-a-s-c-a-l** [comment]
This makes only sense for vector-based layers with transparent areas like, the Urban Atlas layers. These have to be treated differently than raster/grid-based layers (e.g. hazard) where an direct overlap does not work. A calculation a 'differential' layer on client-side doesn't seem to be possible either. 

So maybe we should pick up our initial idea to treat Urban Atlas Layers as additional [Background Layers](https://github.com/clarity-h2020/map-component/issues/3) that are not only available in HC-LE but in any step.  

[Here](https://github.com/clarity-h2020/data-package/issues/5) is a list of potential useful background layers. We have to attach a special tag to the respective resources in the Data Package, so that the map component can decide whether to treat it as background layer or not.

**Comment by DenoBeno** [comment]
considering the "usable layers" from https://github.com/clarity-h2020/data-package/issues/5

**#** | **Layer name** | **Sources**
-- | -- | --
1 | Water | Urban Atlas
2 | Roads | Urban Atlas
3 | Railways | Urban Atlas
4 | Trees | Urban Atlas + Street Tree   layers
5 | Vegetation | Urban Atlas + European   Settlement Map
6 | Agricultural areas | Urban Atlas
7 | Buildings | European Settlement Map
8 | Built open spaces | European Settlement Map
9 | Dense Urban   Fabric | Urban Atlas
10 | Medium Urban Fabric | Urban Atlas
11 | Low Urban Fabric | Urban Atlas
12 | Public, military and industrial units | Urban Atlas
13 | Basins | EU-Hydro
14 | Flow accumulation steams | USGS - HydroSHEDS
15 | DEM | EU-DEM
16 | Surface   Temperature | SL_2_LST_

1-12 are IMO useful. 13 and 14, probably too(?). Not sure about the last two. Surface temperature doesn't sound like a vector layer and no idea what is DEM.

the layers from the second table, no idea. Some of them sound like interesting information, but I think we aren't even showing them at the moment. The third table is quite interesting, but we aren't showing any of this, are we? And I'm not sure if this is vector or grid data.

> So those are the background layers that should be available (at least) in the **HC LE Step**:

![grafik](https://user-images.githubusercontent.com/1788226/48932783-e91e1700-eefd-11e8-8c7c-ddb71dee3152.png)

"Inventory Layers" sound very much like "exposure" to me. I never quite understood why we aren't showing such data under exposure.

**Comment by p-a-s-c-a-l** [comment]
List of multi-selectable background layers is implemented:

![grafik](https://user-images.githubusercontent.com/1788226/67770822-6d0a4880-fa57-11e9-8046-3b9e1947828b.png)

ATM, we use layers tagged with taxonomy term [resource-type:local-effects-parameter](https://csis.myclimateservice.eu/taxonomy/term/1096) to populate the list of background layers. In the future we may introduce a separate resource type, e.g. `background-layer`.

**Comment by DenoBeno** [comment]
Nice. Can we also have a legend for these layers? :-)

**Comment by p-a-s-c-a-l** [comment]
@negroscuro Is it possible to add a legend to the HC-LE input layers?

**Comment by p-a-s-c-a-l** [comment]
done

**Comment by DenoBeno** [comment]
There is one strange effect in the map now. E.g. on https://csis.myclimateservice.eu/study/35/step/1524/view/maps, the background layers are listed once as background (multiple choice possible) and once as default (single choice)

**Comment by p-a-s-c-a-l** [comment]
Yes. Background layers are currently all HC-LE layers as explained [here](https://github.com/clarity-h2020/map-component/issues/65#issuecomment-547418540). Therefore they are duplicated in the HC-LE step. We could  introduce an additional separate resource type, e.g. `background-layer` and then hide those layers in the single choice list.
