### ISSUE TITLE
The loading animation of the map-component does not disappear

### ISSUE THREAD

**Issue by therter** [clarity-h2020/map-component#66]
Sometimes, the initialisation of the map-component does not work and the loading animation will be shown forever.  

![Bildschirmfoto vom 2019-10-25 12-32-24](https://user-images.githubusercontent.com/1788509/67564792-14b80b80-f724-11e9-8a97-909f4ae563f2.png)

This problem is not easy to reproduce. But I can reproduced it relatively frequently in the data package view (e.g. https://csis.myclimateservice.eu/node/682) in my local instance. I have seen this also on the production site, but it is difficult to reproduce.

**Comment by p-a-s-c-a-l** [comment]
I wasn't able to reproduce this problem at all...

Anyway, That's not a problem of the map component. If the loading animation does not go away, then `Drupal.behaviors.mapComponentIFrameConnector` (see [generic-map.html](https://github.com/clarity-h2020/map-component/blob/dev/examples/generic-map.html)) is not called. This function replaces the initial static content of the iFrame (the loading animation) with the actual MapComponent. It calls `initMapComponent` in [csis_iframe_connector.js](https://github.com/clarity-h2020/csis-helpers-module/blob/dev/js/csis_iframe_connector.js#L95).

So I assume that the JavaScript in the Drupal Page is not executed properly. Probably just a caching issue. If you ever encounter this problem again, please check the logs in the JavaScript console.
