### ISSUE TITLE
CSIS study - coastal cities area selection

### ISSUE THREAD

**Issue by mattia-leone** [clarity-h2020/map-component#71]
Selecting a box with a portion in the sea creates this issue

<img width="1275" alt="Schermata 2019-11-26 alle 10 52 13" src="https://user-images.githubusercontent.com/56071027/69619293-abd1f500-103b-11ea-8cc3-c812f280aa4d.png">

The portion of sea should be included in the city borders to perform the study

**Comment by therter** [comment]
>  As Denis suggested we should check whether the study area intersects with the city polygon. ATM you are checking for "contains", right?

That is right, but I can change this.

**Comment by DenoBeno** [comment]
So this is one?

**Comment by therter** [comment]
Yes, this is done
