### ISSUE TITLE
Unnecessary error message "There is no city selected"

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/map-component#78]
E.g. in this [study](https://csis.myclimateservice.eu/study/55/view/area):

![grafik](https://user-images.githubusercontent.com/1788226/73156566-7f3f6580-40de-11ea-81af-35361bdf3317.png)

Some study types like "Expert Studies" or "Basic Screening" don't require a city to be selected. Therefore this error message is misleading. It should only be shown for studies of type Automated Screening.

**Comment by therter** [comment]
At the moment, the "There is no city selected" message will be shown, if no city is selected and the study type of the study contains a calculation method that contains the word emikat within its "Calculation method ID" field.
The word emikat within its "Calculation method ID" field causes also the start of the emikat calculations.

The calculation method of [this study](https://csis.myclimateservice.eu/study/55/view/area)  will be changed to a calculation method that does not trigger emikat and that does not show the message "There is no city selected".
