### ISSUE TITLE
"Digital elevation model" layer should not be always preselected.

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/map-component#81]
Not  a big deal, but I always have to de-select it on a map.

**Comment by DenoBeno** [comment]
It also lacks a legend.

**Comment by p-a-s-c-a-l** [comment]
> It also lacks a legend.

It's coming from the [EEA's WMS](https://discomap.eea.europa.eu/Index/), so unfortunately we no influence on that.

**Comment by p-a-s-c-a-l** [comment]
done
