### ISSUE TITLE
Wrong population distribution layer shown in the map

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/map-component#82]
https://csis.myclimateservice.eu/study/18/step/1904/view/maps only offers the "european population distribution", not the distribution calculated by EMIKAT. 

Ideally, it should be possible to show both IMO.

**Comment by DenoBeno** [comment]
Table shows the correct distribution.

**Comment by p-a-s-c-a-l** [comment]
Somebody changes the respective [resource](https://csis.myclimateservice.eu/node/754/) and introduced a [wrong service path (reference)](https://csis.myclimateservice.eu/node/759):

![grafik](https://user-images.githubusercontent.com/1788226/73639982-bd540080-466d-11ea-8209-c87225ba32c2.png)

So probably somebody duplicated the resource and changed the service which had unwanted side effects as explained [here](https://github.com/clarity-h2020/local-effects/issues/9#issuecomment-579760398).

**Comment by p-a-s-c-a-l** [comment]
@humerh can you please post the correct population exposure EMIKAT URI?

**Comment by humerh** [comment]
Auf der Seite https://github.com/clarity-h2020/csis/wiki/Services-endpoints-(used-by-CSIS)  findet ihr die End-Points

**Comment by p-a-s-c-a-l** [comment]
fixed.

![grafik](https://user-images.githubusercontent.com/1788226/73856648-1078af80-4836-11ea-998c-e22eb7ec520f.png)
