### ISSUE TITLE
Map should not reset after changing a "preset"

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/map-component#83]
This is annoying if one is trying to show how presets change the situation.

**Comment by p-a-s-c-a-l** [comment]
That's a limitation of the iFrame integration. Similar problem as [here](https://github.com/clarity-h2020/map-component/issues/58#issuecomment-535636803). So ATM, there is no easy or quick fix for that.

**Comment by DenoBeno** [comment]
OK, c'est life. It's annoying but it's not a showbreaker. Forget it.
