### ISSUE TITLE
Improve Edit-Mode of Study Area Map

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/map-component#87]
For the user, it's not obvious, that edit mode is activated as reported [here](https://github.com/clarity-h2020/csis/issues/104#issuecomment-597057220). Here at least the title of the "Toggle Edit" Button should change when in edit mode. Furthermore, the EMIKAT calculation is trigged, once the BBOX has been drawn. Instead, it should be trigged only when edit mode is deactivated again. 

When in edit mode, 2 buttons should be shown: *Cancel Edit* and *Save Changes*. Only when pressing *Save Changes*, a (re-)calculation should be triggered.

Additionally, we should 
1) either forbid editing if a bounding box is already set, thus effectively forbid re-calculations at all (see https://github.com/clarity-h2020/emikat/issues/34#issuecomment-595674938)
2) or show a warning to the user that when pressing *Save Changes* the study is re-calculated.

**Comment by patrickkaleta** [comment]
See [this update](https://github.com/clarity-h2020/emikat/issues/34#issuecomment-598285203) for the new Emikat calculation trigger mechanics.

**Comment by therter** [comment]
The buttons Cancel Edit and Save Changes will be shown now, when the edit mode was started.

**Comment by therter** [comment]
The trigger was updated and the study area map was updated, so this issue can be closed
