### ISSUE TITLE
The maps are sometimes not displayed side by side

### ISSUE THREAD

**Issue by therter** [clarity-h2020/map-component#91]
When I click on the Maps button, the maps will be shown side by side, but then when I click on the Maps button again, the maps will be shown one below the other.

![anim](https://user-images.githubusercontent.com/1788509/77421265-cb9bde80-6dcb-11ea-8dee-e481efd9e7fb.gif)

(used Chrome Version 79.0.3945.117 (Offizieller Build) (64-Bit))

**Comment by p-a-s-c-a-l** [comment]
@therter I've updated the css, please try again.

**Comment by therter** [comment]
@p-a-s-c-a-l  Thanks, now I cannot reproduce the error.
