### ISSUE TITLE
Legend Labels missing

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/map-component#94]
[getlegendgraphic shows no label when only one rule is defined](http://osgeo-org.1560.x6.nabble.com/getlegendgraphic-shows-no-label-when-only-one-rule-is-defined-td4909766.html) 
-> append `legend_options=forceLabels:on` to all *GetLegendGraphic* [requests](http://services.clarity-h2020.eu:8080/geoserver/clarity/ows?service=WMS&request=GetLegendGraphic&version=1.1.0&format=image%2Fpng&layer=clarity:public_military_industrial&legend_options=forceLabels:on).

**Comment by negroscuro** [comment]
I understand this is fixed, but honestly I do not understand why the force label option is needed, I would expect to have it orking without it but it seems necessary... 

http://services.clarity-h2020.eu:8080/geoserver/wms?REQUEST=GetLegendGraphic&VERSION=1.1.0&FORMAT=image/png&WIDTH=20&HEIGHT=20&LAYER=clarity:agricultural_areas&legend_options=forceLabels:on

**Comment by therter** [comment]
this is fixed now
